########################
# iControlU Plugin.yml #
########################
name: iControlU
version: 2.4.8
main: tech.hadenw.icontrolu.plugin.iControlU
author: FireBreath15
softdepend: [ProtocolLib]
api-version: 1.13
commands:
  icu:
permissions:
  icu.control.*:
    children:
      icu.use: true
      icu.control: true
      icu.control.other: true
      icu.control.nearest: true
      icu.forcechat: true
      icu.simple: true
      icu.readchat: true
  icu.admin:
    children:
      icu.exempt: true
      icu.control.*: true
      icu.nocooldown: true
      icu.notimelimit: true
      icu.reload: true
  icu.use:
    default: op
  icu.control:
    default: op
  icu.control.other:
    default: op
  icu.exempt:
    default: false
  icu.chat:
    default: false
  icu.reload:
    default: op
  icu.control.nearest:
    default: op
  icu.forcechat:
    default: op
  icu.readchat:
    default: op
  icu.nocooldown:
    default: false
  icu.notimelimit:
    default: false
  icu.simple:
    default: op